# Generated by Django 4.1 on 2022-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_lots_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='close_lot_datetime',
            field=models.DateTimeField(),
        ),
    ]
