# Generated by Django 4.1 on 2022-09-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_lots_close_lot_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='name_buyer_lot',
        ),
    ]
