# Generated by Django 4.1 on 2022-09-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_lots_name_buyer_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='name_user',
        ),
        migrations.AddField(
            model_name='lots',
            name='name_buyer_lot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lots',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Seller_Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_seller', models.CharField(db_index=True, max_length=50)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.lots')),
            ],
        ),
    ]
