# Generated by Django 4.1 on 2022-09-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_lots_name_buyer_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='cost_initial',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='cost_lot',
        ),
        migrations.AlterField(
            model_name='lots',
            name='image_lot1',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image_lot2',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image_lot3',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image_lot4',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image_lot5',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image_lot6',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='main_image_lot',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
    ]
