# Generated by Django 4.1 on 2022-09-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_lots_cost_initial_remove_lots_cost_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='cost_initial',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lots',
            name='cost_lot',
            field=models.FloatField(default=0),
        ),
    ]
