# Generated by Django 4.1 on 2022-09-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_lots_cost_initial_alter_lots_cost_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='close_lot_datetime',
        ),
    ]
