# Generated by Django 4.1 on 2022-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_lots_close_lot_date_lots_close_lot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='close_lot_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
