# Generated by Django 4.1 on 2022-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_category_id_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_lot',
            field=models.IntegerField(null=True),
        ),
    ]
