# Generated by Django 4.1 on 2022-09-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_category_id_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lots',
            name='image_lot1',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='image_lot2',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='image_lot3',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='image_lot4',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='image_lot5',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='image_lot6',
        ),
        migrations.RemoveField(
            model_name='lots',
            name='main_image_lot',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>')),
                ('title', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.lots')),
            ],
        ),
    ]
