# Generated by Django 4.1 on 2022-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_lots_image_delete_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lots',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='lots',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='lots',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='lots',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='lots',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='lots',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='lots',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
        migrations.AddField(
            model_name='lots',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/<django.db.models.fields.AutoField>'),
        ),
    ]
