
# Generated by Django 4.1 on 2022-09-17 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_lots_image1_alter_lots_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='Photo/'),
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_Coment', models.TextField(verbose_name='Information for lot')),
                ('coment_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
