# Generated by Django 4.1 on 2022-09-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_lots_image3_alter_lots_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='that_commented',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.lots'),
        ),
        migrations.AlterField(
            model_name='coments',
            name='text_Coment',
            field=models.TextField(verbose_name='Coment'),
        ),
    ]
